function love.conf(t)
    t.modules.joystick = true   -- Enable the joystick module (boolean)
    t.modules.audio = true      -- Enable the audio module (boolean)
    t.modules.keyboard = true   -- Enable the keyboard module (boolean)
    t.modules.event = true      -- Enable the event module (boolean)
    t.modules.image = true      -- Enable the image module (boolean)
    t.modules.graphics = true   -- Enable the graphics module (boolean)
    t.modules.timer = true      -- Enable the timer module (boolean)
    t.modules.mouse = true      -- Enable the mouse module (boolean)
    t.modules.sound = true      -- Enable the sound module (boolean)
    t.modules.physics = true    -- Enable the physics module (boolean)
	
    t.console = false           -- Attach a console (boolean, Windows only)
    t.title = "Geomancer Shepherd"   -- The title of the window the game is in (string)
    t.author = "elcow"          -- The author of the game (string)
	t.identity = nil			-- The name of the save directory (string)
    t.screen.fullscreen = false -- Enable fullscreen (boolean)
    t.screen.vsync = true       -- Enable vertical sync (boolean)
    t.screen.fsaa = 0           -- The number of FSAA-buffers (number)
    t.screen.height = 540       -- The window height (number)
    t.screen.width = 960        -- The window width (number)
    t.version = 0.72            -- The LÖVE version this game was made for (number)
	t.release = true            -- Enable release mode (boolean)
end
